name:                functionsAndDragons
version:             0.1.0.0
github:              "githubuser/functionsAndDragons"
license:             BSD3
author:              "Peter Taylor"
maintainer:          "example@example.com"
copyright:           "2021 Peter Taylor"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/functionsAndDragons#readme>

dependencies:
- base >= 4.9 && < 5
- unordered-containers
- hashable
- transformers

library:
  source-dirs: src

executables:
  functionsAndDragons-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functionsAndDragons

tests:
  functionsAndDragons-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functionsAndDragons
